// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace PyxelSharp.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "pyxel_bind_cs";





        /// <summary>
        ///  Returns the message of the last failed call. The pointer stays valid until
        ///  the next failing call on the same thread.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_last_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* pyxel_last_error();

        /// <summary>
        ///  # Safety
        ///  `title` must be null or a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_init(uint width, uint height, byte* title, uint fps, uint quit_key, uint display_scale, uint capture_scale, uint capture_sec, int headless);

        [DllImport(__DllName, EntryPoint = "pyxel_run", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_run(delegate* unmanaged[Cdecl]<void> update, delegate* unmanaged[Cdecl]<void> draw);

        [DllImport(__DllName, EntryPoint = "pyxel_show", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_show();

        [DllImport(__DllName, EntryPoint = "pyxel_flip", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_flip();

        [DllImport(__DllName, EntryPoint = "pyxel_quit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_quit();

        /// <summary>
        ///  Restarts the application (Python: `pyxel.reset`).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_reset();

        /// <summary>
        ///  Sets the window icon from rows of hex color digits
        ///  (Python: `pyxel.icon`). `colkey` uses -1 as the None sentinel.
        ///
        ///  # Safety
        ///  `data` must point to `data_len` valid NUL-terminated UTF-8 strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_icon", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_icon(byte** data, uint data_len, uint scale, int colkey);

        /// <summary>
        ///  Restricts display scaling to integer factors (Python: `pyxel.integer_scale`).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_integer_scale", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_integer_scale([MarshalAs(UnmanagedType.U1)] bool enabled);

        /// <summary>
        ///  Switches the screen shader mode (Python: `pyxel.screen_mode`).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_screen_mode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_screen_mode(uint screen_mode);

        /// <summary>
        ///  Resizes the screen (Python: `pyxel.resize`).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_resize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_resize(uint width, uint height);

        /// <summary>
        ///  # Safety
        ///  `title` must be a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_title", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_title(byte* title);

        [DllImport(__DllName, EntryPoint = "pyxel_fullscreen", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_fullscreen([MarshalAs(UnmanagedType.U1)] bool enabled);

        [DllImport(__DllName, EntryPoint = "pyxel_perf_monitor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_perf_monitor([MarshalAs(UnmanagedType.U1)] bool enabled);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_frame_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_frame_count(uint* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_width", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_width(uint* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_height", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_height(uint* out_value);

        /// <summary>
        ///  Plays sound bank indices on channel `ch` (Python: `pyxel.play`).
        ///  `sec` uses NaN as the None sentinel.
        ///
        ///  # Safety
        ///  `sounds` must point to `sounds_len` u32 values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_play", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_play(uint ch, uint* sounds, uint sounds_len, float sec, [MarshalAs(UnmanagedType.U1)] bool should_loop, [MarshalAs(UnmanagedType.U1)] bool resume);

        /// <summary>
        ///  Plays sound handles on channel `ch` (Python: `pyxel.play` with Sound
        ///  objects). `sec` uses NaN as the None sentinel.
        ///
        ///  # Safety
        ///  `sounds` must point to `sounds_len` live sound handles.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_play_handles", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_play_handles(uint ch, void** sounds, uint sounds_len, float sec, [MarshalAs(UnmanagedType.U1)] bool should_loop, [MarshalAs(UnmanagedType.U1)] bool resume);

        /// <summary>
        ///  Plays MML code on channel `ch` (Python: `pyxel.play` with a string).
        ///  `sec` uses NaN as the None sentinel.
        ///
        ///  # Safety
        ///  `code` must be a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_play_mml", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_play_mml(uint ch, byte* code, float sec, [MarshalAs(UnmanagedType.U1)] bool should_loop, [MarshalAs(UnmanagedType.U1)] bool resume);

        /// <summary>
        ///  Plays music bank `msc` (Python: `pyxel.playm`). `sec` uses NaN as the
        ///  None sentinel.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_playm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_playm(uint msc, float sec, [MarshalAs(UnmanagedType.U1)] bool should_loop);

        /// <summary>
        ///  Stops channel `ch`, or every channel when `ch` is negative
        ///  (Python: `pyxel.stop`).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_stop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_stop(int ch);

        /// <summary>
        ///  Current (sound index, seconds) of channel `ch`; `out_has_value` is false
        ///  when nothing is playing (Python: `pyxel.play_pos`).
        ///
        ///  # Safety
        ///  The out pointers must be writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_play_pos", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_play_pos(uint ch, uint* out_sound_index, float* out_sec, bool* out_has_value);

        /// <summary>
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_channel_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_channel_new(void** out_handle);

        /// <summary>
        ///  Returns a handle to the mixer channel `pyxel.channels[index]`.
        ///
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_channel_bank", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_channel_bank(uint index, void** out_handle);

        /// <summary>
        ///  Number of mixer channels (`pyxel::NUM_CHANNELS`).
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_num_channels", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_num_channels(uint* out_value);

        /// <summary>
        ///  Releases the handle's `Arc` clone (safe from any thread).
        ///
        ///  # Safety
        ///  `handle` must be a live handle; it is invalid after this call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_channel_drop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_channel_drop(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_channel_gain", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_channel_gain(void* handle, float* out_value);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_channel_set_gain", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_channel_set_gain(void* handle, float gain);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_channel_detune", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_channel_detune(void* handle, int* out_value);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_channel_set_detune", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_channel_set_detune(void* handle, int detune);

        /// <summary>
        ///  Plays `sounds_len` sound handles in order (Python: `channel.play`).
        ///  `sec` uses NaN as the None sentinel.
        ///
        ///  # Safety
        ///  `handle` must be a live channel handle; `sounds` must point to
        ///  `sounds_len` live sound handles.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_channel_play", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_channel_play(void* handle, void** sounds, uint sounds_len, float sec, [MarshalAs(UnmanagedType.U1)] bool should_loop, [MarshalAs(UnmanagedType.U1)] bool resume);

        /// <summary>
        ///  Plays MML code (Python: `channel.play(mml)`). `sec` uses NaN as the None
        ///  sentinel.
        ///
        ///  # Safety
        ///  `handle` must be a live channel handle and `code` valid NUL-terminated
        ///  UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_channel_play_mml", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_channel_play_mml(void* handle, byte* code, float sec, [MarshalAs(UnmanagedType.U1)] bool should_loop, [MarshalAs(UnmanagedType.U1)] bool resume);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live channel handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_channel_stop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_channel_stop(void* handle);

        /// <summary>
        ///  Current (sound index, seconds) of playback; `out_has_value` is false when
        ///  nothing is playing (Python: `channel.play_pos`).
        ///
        ///  # Safety
        ///  `handle` must be a live channel handle; the out pointers writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_channel_play_pos", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_channel_play_pos(void* handle, uint* out_sound_index, float* out_sec, bool* out_has_value);

        /// <summary>
        ///  Loads a BDF or TTF font; `font_size` (NaN = default) applies to TTF.
        ///
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string; `out_handle` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_font_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_font_new(byte* filename, float font_size, void** out_handle);

        /// <summary>
        ///  Releases the handle's `Rc` clone. Must be called on the pyxel thread.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; it is invalid after this call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_font_drop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_font_drop(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle; `text` a valid NUL-terminated UTF-8
        ///  string; `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_font_text_width", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_font_text_width(void* handle, byte* text, int* out_value);

        [DllImport(__DllName, EntryPoint = "pyxel_cls", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_cls(byte color);

        /// <summary>
        ///  # Safety
        ///  `out_color` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_pget", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_pget(float x, float y, byte* out_color);

        [DllImport(__DllName, EntryPoint = "pyxel_pset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_pset(float x, float y, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_line", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_line(float x1, float y1, float x2, float y2, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_rect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_rect(float x, float y, float width, float height, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_rectb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_rectb(float x, float y, float width, float height, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_circ", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_circ(float x, float y, float radius, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_circb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_circb(float x, float y, float radius, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_elli", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_elli(float x, float y, float width, float height, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_ellib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_ellib(float x, float y, float width, float height, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_tri", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tri(float x1, float y1, float x2, float y2, float x3, float y3, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_trib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_trib(float x1, float y1, float x2, float y2, float x3, float y3, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_fill", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_fill(float x, float y, byte color);

        /// <summary>
        ///  # Safety
        ///  `text` must be a valid NUL-terminated UTF-8 string and `font` null
        ///  (built-in font) or a live font handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_text(float x, float y, byte* text, byte color, void* font);

        /// <summary>
        ///  Blits from a source image handle to the screen. `colkey` uses -1 as the
        ///  None sentinel, `rotate` / `scale` use NaN.
        ///
        ///  # Safety
        ///  `image` must be a live handle returned by one of the `pyxel_image_*` /
        ///  `pyxel_screen` constructors.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_blt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_blt(float x, float y, void* image, float u, float v, float width, float height, int colkey, float rotate, float scale);

        /// <summary>
        ///  Draws a region of a tilemap onto the screen (Python: `pyxel.bltm`).
        ///  `colkey` uses -1 as the None sentinel, `rotate` / `scale` use NaN.
        ///
        ///  # Safety
        ///  `tilemap` must be a live tilemap handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_bltm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_bltm(float x, float y, void* tilemap, float u, float v, float width, float height, int colkey, float rotate, float scale);

        /// <summary>
        ///  Perspective-projects a region of an image onto the screen
        ///  (Python: `pyxel.blt3d`). `fov` uses NaN and `colkey` -1 as None sentinels.
        ///
        ///  # Safety
        ///  `image` must be a live image handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_blt3d", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_blt3d(float x, float y, float width, float height, void* image, float pos_x, float pos_y, float pos_z, float rot_x, float rot_y, float rot_z, float fov, int colkey);

        /// <summary>
        ///  Perspective-projects a region of a tilemap onto the screen
        ///  (Python: `pyxel.bltm3d`). `fov` uses NaN and `colkey` -1 as None sentinels.
        ///
        ///  # Safety
        ///  `tilemap` must be a live tilemap handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_bltm3d", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_bltm3d(float x, float y, float width, float height, void* tilemap, float pos_x, float pos_y, float pos_z, float rot_x, float rot_y, float rot_z, float fov, int colkey);

        [DllImport(__DllName, EntryPoint = "pyxel_clip", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_clip(float x, float y, float width, float height);

        [DllImport(__DllName, EntryPoint = "pyxel_clip_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_clip_reset();

        [DllImport(__DllName, EntryPoint = "pyxel_camera", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_camera(float x, float y);

        [DllImport(__DllName, EntryPoint = "pyxel_camera_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_camera_reset();

        [DllImport(__DllName, EntryPoint = "pyxel_dither", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_dither(float alpha);

        [DllImport(__DllName, EntryPoint = "pyxel_pal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_pal(byte src_color, byte dst_color);

        [DllImport(__DllName, EntryPoint = "pyxel_pal_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_pal_reset();

        /// <summary>
        ///  Number of display palette entries (Python: `len(pyxel.colors)`).
        ///
        ///  # Safety
        ///  `out_len` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_colors_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_colors_len(uint* out_len);

        /// <summary>
        ///  Reads display palette entry `index` as 0xRRGGBB
        ///  (Python: `pyxel.colors[i]`).
        ///
        ///  # Safety
        ///  `out_rgb` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_colors_get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_colors_get(uint index, uint* out_rgb);

        /// <summary>
        ///  Writes display palette entry `index` as 0xRRGGBB
        ///  (Python: `pyxel.colors[i] = rgb`).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_colors_set", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_colors_set(uint index, uint rgb);

        /// <summary>
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_new(uint width, uint height, void** out_handle);

        /// <summary>
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string and `out_handle`
        ///  must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_from_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_from_image(byte* filename, int include_colors, void** out_handle);

        /// <summary>
        ///  Returns a handle to the image bank `pyxel.images[index]`.
        ///
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_bank", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_bank(uint index, void** out_handle);

        /// <summary>
        ///  Returns a handle to the screen image `pyxel.screen`.
        ///
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_screen", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_screen(void** out_handle);

        /// <summary>
        ///  Returns a handle to the mouse cursor image `pyxel.cursor`.
        ///
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_cursor_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_cursor_image(void** out_handle);

        /// <summary>
        ///  Returns a handle to the built-in font image `pyxel.font`.
        ///
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_font_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_font_image(void** out_handle);

        /// <summary>
        ///  Number of image banks (`pyxel::NUM_IMAGES`).
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_num_images", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_num_images(uint* out_value);

        /// <summary>
        ///  Releases the handle's `Rc` clone. Must be called on the pyxel thread.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; it is invalid after this call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_drop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_drop(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_width", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_width(void* handle, uint* out_value);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_height", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_height(void* handle, uint* out_value);

        /// <summary>
        ///  Pointer to the image's pixel buffer (`width * height` color indices).
        ///  Valid while the image is alive and its size unchanged.
        ///
        ///  # Safety
        ///  `handle` must be a live handle and `out_ptr` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_data_ptr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_data_ptr(void* handle, byte** out_ptr);

        /// <summary>
        ///  Writes rows of hex color digits (`data`, `data_len` strings) at (x, y),
        ///  like Python's `image.set`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `data` must point to `data_len` valid
        ///  NUL-terminated UTF-8 strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_set", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_set(void* handle, int x, int y, byte** data, uint data_len);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `filename` a valid NUL-terminated
        ///  UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_load", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_load(void* handle, int x, int y, byte* filename, int include_colors);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `filename` a valid NUL-terminated
        ///  UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_save", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_save(void* handle, byte* filename, uint scale);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_clip", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_clip(void* handle, float x, float y, float width, float height);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_clip_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_clip_reset(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_camera", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_camera(void* handle, float x, float y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_camera_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_camera_reset(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_pal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_pal(void* handle, byte src_color, byte dst_color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_pal_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_pal_reset(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_dither", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_dither(void* handle, float alpha);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_cls", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_cls(void* handle, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_color` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_pget", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_pget(void* handle, float x, float y, byte* out_color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_pset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_pset(void* handle, float x, float y, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_line", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_line(void* handle, float x1, float y1, float x2, float y2, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_rect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_rect(void* handle, float x, float y, float width, float height, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_rectb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_rectb(void* handle, float x, float y, float width, float height, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_circ", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_circ(void* handle, float x, float y, float radius, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_circb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_circb(void* handle, float x, float y, float radius, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_elli", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_elli(void* handle, float x, float y, float width, float height, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_ellib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_ellib(void* handle, float x, float y, float width, float height, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_tri", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_tri(void* handle, float x1, float y1, float x2, float y2, float x3, float y3, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_trib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_trib(void* handle, float x1, float y1, float x2, float y2, float x3, float y3, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_fill", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_fill(void* handle, float x, float y, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle, `text` a valid NUL-terminated UTF-8
        ///  string, and `font` null (built-in font) or a live font handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_text(void* handle, float x, float y, byte* text, byte color, void* font);

        /// <summary>
        ///  Draws a region of a tilemap onto `handle` (Python: &lt;c&gt;image.bltm&lt;/c&gt;).
        ///  `colkey` uses -1 as the None sentinel, `rotate` / `scale` use NaN.
        ///
        ///  # Safety
        ///  `handle` must be a live image handle and `tilemap` a live tilemap handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_bltm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_bltm(void* handle, float x, float y, void* tilemap, float u, float v, float width, float height, int colkey, float rotate, float scale);

        /// <summary>
        ///  Perspective-projects a region of a source image onto `handle`
        ///  (Python: `image.blt3d`). `fov` uses NaN and `colkey` -1 as None sentinels.
        ///
        ///  # Safety
        ///  `handle` and `source` must be live image handles.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_blt3d", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_blt3d(void* handle, float x, float y, float width, float height, void* source, float pos_x, float pos_y, float pos_z, float rot_x, float rot_y, float rot_z, float fov, int colkey);

        /// <summary>
        ///  Perspective-projects a region of a tilemap onto `handle`
        ///  (Python: `image.bltm3d`). `fov` uses NaN and `colkey` -1 as None sentinels.
        ///
        ///  # Safety
        ///  `handle` must be a live image handle and `tilemap` a live tilemap handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_bltm3d", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_bltm3d(void* handle, float x, float y, float width, float height, void* tilemap, float pos_x, float pos_y, float pos_z, float rot_x, float rot_y, float rot_z, float fov, int colkey);

        /// <summary>
        ///  Blits from `source` onto `handle`. `colkey` uses -1 as the None sentinel,
        ///  `rotate` / `scale` use NaN.
        ///
        ///  # Safety
        ///  `handle` and `source` must be live handles.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_blt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_blt(void* handle, float x, float y, void* source, float u, float v, float width, float height, int colkey, float rotate, float scale);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_btn", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_btn(uint key, bool* out_value);

        /// <summary>
        ///  `hold_frames` / `repeat_frames` use `u32::MAX` as the None sentinel.
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_btnp", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_btnp(uint key, uint hold_frames, uint repeat_frames, bool* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_btnr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_btnr(uint key, bool* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_btnv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_btnv(uint key, int* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_mouse_x", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_mouse_x(int* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_mouse_y", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_mouse_y(int* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_mouse_wheel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_mouse_wheel(int* out_value);

        [DllImport(__DllName, EntryPoint = "pyxel_mouse", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_mouse([MarshalAs(UnmanagedType.U1)] bool visible);

        [DllImport(__DllName, EntryPoint = "pyxel_warp_mouse", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_warp_mouse(float x, float y);

        /// <summary>
        ///  Text typed since the last frame (Python: `pyxel.input_text`). The pointer
        ///  written to `out_text` stays valid until the next string-returning call on
        ///  this thread.
        ///
        ///  # Safety
        ///  `out_text` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_input_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_input_text(byte** out_text);

        /// <summary>
        ///  Number of keys currently held (Python: `len(pyxel.input_keys)`).
        ///
        ///  # Safety
        ///  `out_len` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_input_keys_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_input_keys_len(uint* out_len);

        /// <summary>
        ///  Copies up to `buffer_len` held key codes into `buffer`
        ///  (Python: `pyxel.input_keys`).
        ///
        ///  # Safety
        ///  `buffer` must hold `buffer_len` u32 values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_input_keys_read", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_input_keys_read(uint* buffer, uint buffer_len);

        /// <summary>
        ///  Number of files dropped onto the window this frame
        ///  (Python: `len(pyxel.dropped_files)`).
        ///
        ///  # Safety
        ///  `out_len` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_dropped_files_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_dropped_files_len(uint* out_len);

        /// <summary>
        ///  Path of dropped file `index` (Python: `pyxel.dropped_files[i]`). The
        ///  pointer written to `out_path` stays valid until the next string-returning
        ///  call on this thread.
        ///
        ///  # Safety
        ///  `out_path` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_dropped_file", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_dropped_file(uint index, byte** out_path);

        /// <summary>
        ///  Overrides a key state for the current frame (Python: `pyxel.set_btn`,
        ///  mainly for tests).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_set_btn", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_set_btn(uint key, [MarshalAs(UnmanagedType.U1)] bool state);

        /// <summary>
        ///  Overrides an analog key value for the current frame
        ///  (Python: `pyxel.set_btnv`).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_set_btnv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_set_btnv(uint key, int value);

        /// <summary>
        ///  Overrides the typed text for the current frame
        ///  (Python: `pyxel.set_input_text`).
        ///
        ///  # Safety
        ///  `text` must be a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_set_input_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_set_input_text(byte* text);

        /// <summary>
        ///  Overrides the dropped-file list for the current frame
        ///  (Python: `pyxel.set_dropped_files`).
        ///
        ///  # Safety
        ///  `files` must point to `files_len` valid NUL-terminated UTF-8 strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_set_dropped_files", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_set_dropped_files(byte** files, uint files_len);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_ceil", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_ceil(float x, int* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_floor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_floor(float x, int* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sqrt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sqrt(float x, float* out_value);

        /// <summary>
        ///  Sine of an angle in degrees.
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sin", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sin(float deg, float* out_value);

        /// <summary>
        ///  Cosine of an angle in degrees.
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_cos", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_cos(float deg, float* out_value);

        /// <summary>
        ///  Arctangent of y/x in degrees.
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_atan2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_atan2(float y, float x, float* out_value);

        [DllImport(__DllName, EntryPoint = "pyxel_rseed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_rseed(uint seed);

        /// <summary>
        ///  Random integer in [a, b].
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_rndi", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_rndi(int a, int b, int* out_value);

        /// <summary>
        ///  Random float in [a, b].
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_rndf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_rndf(float a, float b, float* out_value);

        [DllImport(__DllName, EntryPoint = "pyxel_nseed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_nseed(uint seed);

        /// <summary>
        ///  Perlin noise at (x, y, z).
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_noise", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_noise(float x, float y, float z, float* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_music_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_music_new(void** out_handle);

        /// <summary>
        ///  Returns a handle to the music bank `pyxel.musics[index]`.
        ///
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_music_bank", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_music_bank(uint index, void** out_handle);

        /// <summary>
        ///  Number of music banks (`pyxel::NUM_MUSICS`).
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_num_musics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_num_musics(uint* out_value);

        /// <summary>
        ///  Releases the handle's `Arc` clone (safe from any thread).
        ///
        ///  # Safety
        ///  `handle` must be a live handle; it is invalid after this call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_music_drop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_music_drop(void* handle);

        /// <summary>
        ///  Number of sequences (Python: `len(music.seqs)`).
        ///
        ///  # Safety
        ///  `handle` must be a live handle and `out_len` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_music_seqs_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_music_seqs_len(void* handle, uint* out_len);

        /// <summary>
        ///  Length of sequence `index`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle and `out_len` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_music_seq_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_music_seq_len(void* handle, uint index, uint* out_len);

        /// <summary>
        ///  Copies up to `buffer_len` sound indices of sequence `index` into `buffer`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `buffer` must hold `buffer_len` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_music_seq_read", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_music_seq_read(void* handle, uint index, uint* buffer, uint buffer_len);

        /// <summary>
        ///  Replaces sequence `index` with `data_len` sound indices from `data`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `data` must hold `data_len` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_music_seq_write", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_music_seq_write(void* handle, uint index, uint* data, uint data_len);

        /// <summary>
        ///  Removes all sequences.
        ///
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_music_seqs_clear", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_music_seqs_clear(void* handle);

        /// <summary>
        ///  Appends a sequence of `data_len` sound indices.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `data` must hold `data_len` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_music_seqs_append", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_music_seqs_append(void* handle, uint* data, uint data_len);

        /// <summary>
        ///  Renders `sec` seconds to a WAV file (Python: `music.save`).
        ///
        ///  # Safety
        ///  `handle` must be a live handle and `filename` valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_music_save", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_music_save(void* handle, byte* filename, float sec, int ffmpeg);

        /// <summary>
        ///  Loads a .pyxres resource file. The `exclude_*` flags are `i32` opt-bools
        ///  (-1 = None).
        ///
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_load", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_load(byte* filename, int exclude_images, int exclude_tilemaps, int exclude_sounds, int exclude_musics);

        /// <summary>
        ///  Saves a .pyxres resource file. The `exclude_*` flags are `i32` opt-bools
        ///  (-1 = None).
        ///
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_save", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_save(byte* filename, int exclude_images, int exclude_tilemaps, int exclude_sounds, int exclude_musics);

        /// <summary>
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_load_pal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_load_pal(byte* filename);

        /// <summary>
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_save_pal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_save_pal(byte* filename);

        /// <summary>
        ///  Saves a screenshot; a null `filename` uses a timestamped desktop path.
        ///  `scale` uses `u32::MAX` as the None sentinel.
        ///
        ///  # Safety
        ///  `filename` must be null or a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_screenshot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_screenshot(byte* filename, uint scale);

        /// <summary>
        ///  Saves the recent frames as a GIF; a null `filename` uses a timestamped
        ///  desktop path. `scale` uses `u32::MAX` as the None sentinel.
        ///
        ///  # Safety
        ///  `filename` must be null or a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_screencast", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_screencast(byte* filename, uint scale);

        [DllImport(__DllName, EntryPoint = "pyxel_reset_screencast", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_reset_screencast();

        /// <summary>
        ///  Returns the per-user data directory for the app. The pointer written to
        ///  `out_path` stays valid until the next string-returning call on this thread.
        ///
        ///  # Safety
        ///  `vendor_name` and `app_name` must be valid NUL-terminated UTF-8 strings;
        ///  `out_path` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_user_data_dir", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_user_data_dir(byte* vendor_name, byte* app_name, byte** out_path);

        /// <summary>
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_new(void** out_handle);

        /// <summary>
        ///  Returns a handle to the sound bank `pyxel.sounds[index]`.
        ///
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_bank", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_bank(uint index, void** out_handle);

        /// <summary>
        ///  Number of sound banks (`pyxel::NUM_SOUNDS`).
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_num_sounds", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_num_sounds(uint* out_value);

        /// <summary>
        ///  Releases the handle's `Arc` clone (safe from any thread).
        ///
        ///  # Safety
        ///  `handle` must be a live handle; it is invalid after this call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_drop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_drop(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_len` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_notes_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_notes_len(void* handle, uint* out_len);

        /// <summary>
        ///  Copies up to `buffer_len` notes into `buffer`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `buffer` must hold `buffer_len` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_notes_read", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_notes_read(void* handle, sbyte* buffer, uint buffer_len);

        /// <summary>
        ///  Replaces the note list with `data_len` values from `data`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `data` must hold `data_len` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_notes_write", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_notes_write(void* handle, sbyte* data, uint data_len);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_len` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_tones_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_tones_len(void* handle, uint* out_len);

        /// <summary>
        ///  Copies up to `buffer_len` tone indices into `buffer`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `buffer` must hold `buffer_len` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_tones_read", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_tones_read(void* handle, byte* buffer, uint buffer_len);

        /// <summary>
        ///  Replaces the tone list with `data_len` values from `data`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `data` must hold `data_len` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_tones_write", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_tones_write(void* handle, byte* data, uint data_len);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_len` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_volumes_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_volumes_len(void* handle, uint* out_len);

        /// <summary>
        ///  Copies up to `buffer_len` volumes into `buffer`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `buffer` must hold `buffer_len` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_volumes_read", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_volumes_read(void* handle, byte* buffer, uint buffer_len);

        /// <summary>
        ///  Replaces the volume list with `data_len` values from `data`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `data` must hold `data_len` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_volumes_write", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_volumes_write(void* handle, byte* data, uint data_len);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_len` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_effects_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_effects_len(void* handle, uint* out_len);

        /// <summary>
        ///  Copies up to `buffer_len` effects into `buffer`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `buffer` must hold `buffer_len` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_effects_read", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_effects_read(void* handle, byte* buffer, uint buffer_len);

        /// <summary>
        ///  Replaces the effect list with `data_len` values from `data`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `data` must hold `data_len` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_effects_write", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_effects_write(void* handle, byte* data, uint data_len);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_speed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_speed(void* handle, ushort* out_value);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_set_speed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_set_speed(void* handle, ushort speed);

        /// <summary>
        ///  Sets all components from their string notations (Python: `sound.set`).
        ///
        ///  # Safety
        ///  `handle` must be a live handle; the strings must be valid NUL-terminated
        ///  UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_set", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_set(void* handle, byte* notes, byte* tones, byte* volumes, byte* effects, ushort speed);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `notes` valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_set_notes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_set_notes(void* handle, byte* notes);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `tones` valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_set_tones", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_set_tones(void* handle, byte* tones);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `volumes` valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_set_volumes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_set_volumes(void* handle, byte* volumes);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `effects` valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_set_effects", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_set_effects(void* handle, byte* effects);

        /// <summary>
        ///  Sets the MML code, or clears it when `code` is null (Python: `sound.mml`).
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `code` null or valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_mml", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_mml(void* handle, byte* code);

        /// <summary>
        ///  Loads a PCM file, or clears the PCM data when `filename` is null
        ///  (Python: `sound.pcm`).
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `filename` null or valid NUL-terminated
        ///  UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_pcm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_pcm(void* handle, byte* filename);

        /// <summary>
        ///  Renders `sec` seconds to a WAV file (Python: `sound.save`).
        ///
        ///  # Safety
        ///  `handle` must be a live handle and `filename` valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_save", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_save(void* handle, byte* filename, float sec, int ffmpeg);

        /// <summary>
        ///  Playback length in seconds; `out_has_value` is false when unknown
        ///  (Python: `sound.total_sec`).
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `out_value` and `out_has_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_sound_total_sec", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_sound_total_sec(void* handle, float* out_value, bool* out_has_value);

        /// <summary>
        ///  Creates a tilemap whose tiles reference either the image bank `image_index`
        ///  (when `image` is null) or the given image handle.
        ///
        ///  # Safety
        ///  `image` must be null or a live image handle; `out_handle` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_new(uint width, uint height, void* image, uint image_index, void** out_handle);

        /// <summary>
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string; `out_handle` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_from_tmx", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_from_tmx(byte* filename, uint layer, void** out_handle);

        /// <summary>
        ///  Returns a handle to the tilemap bank `pyxel.tilemaps[index]`.
        ///
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_bank", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_bank(uint index, void** out_handle);

        /// <summary>
        ///  Number of tilemap banks (`pyxel::NUM_TILEMAPS`).
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_num_tilemaps", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_num_tilemaps(uint* out_value);

        /// <summary>
        ///  Releases the handle's `Rc` clone. Must be called on the pyxel thread.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; it is invalid after this call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_drop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_drop(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_width", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_width(void* handle, uint* out_value);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_height", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_height(void* handle, uint* out_value);

        /// <summary>
        ///  Reads the image source: bank index into `out_index` (with `out_image` set
        ///  to null), or a new image handle into `out_image` (with `out_index` -1).
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `out_index` and `out_image` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_imgsrc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_imgsrc(void* handle, int* out_index, void** out_image);

        /// <summary>
        ///  Points the tilemap at an image bank or (non-null `image`) an image handle.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `image` null or a live image handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_set_imgsrc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_set_imgsrc(void* handle, void* image, uint image_index);

        /// <summary>
        ///  Pointer to the tile buffer (`width * height` tiles, two u16 each).
        ///  Valid while the tilemap is alive and its size unchanged.
        ///
        ///  # Safety
        ///  `handle` must be a live handle and `out_ptr` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_data_ptr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_data_ptr(void* handle, ushort** out_ptr);

        /// <summary>
        ///  Writes rows of tile data at (x, y), like Python's `tilemap.set`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `data` must point to `data_len` valid
        ///  NUL-terminated UTF-8 strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_set", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_set(void* handle, int x, int y, byte** data, uint data_len);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `filename` a valid NUL-terminated
        ///  UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_load", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_load(void* handle, int x, int y, byte* filename, uint layer);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_clip", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_clip(void* handle, float x, float y, float width, float height);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_clip_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_clip_reset(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_camera", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_camera(void* handle, float x, float y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_camera_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_camera_reset(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_cls", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_cls(void* handle, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle; `out_tile_x` and `out_tile_y` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_pget", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_pget(void* handle, float x, float y, ushort* out_tile_x, ushort* out_tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_pset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_pset(void* handle, float x, float y, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_line", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_line(void* handle, float x1, float y1, float x2, float y2, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_rect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_rect(void* handle, float x, float y, float width, float height, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_rectb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_rectb(void* handle, float x, float y, float width, float height, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_circ", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_circ(void* handle, float x, float y, float radius, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_circb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_circb(void* handle, float x, float y, float radius, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_elli", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_elli(void* handle, float x, float y, float width, float height, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_ellib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_ellib(void* handle, float x, float y, float width, float height, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_tri", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_tri(void* handle, float x1, float y1, float x2, float y2, float x3, float y3, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_trib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_trib(void* handle, float x1, float y1, float x2, float y2, float x3, float y3, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_fill", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_fill(void* handle, float x, float y, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  Slides a rect by (dx, dy) against wall tiles, returning the allowed
        ///  movement (Python: `tilemap.collide`). `walls` is `walls_len` tiles laid
        ///  out as u16 pairs.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `walls` must point to `walls_len * 2`
        ///  u16 values; `out_dx` and `out_dy` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_collide", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_collide(void* handle, float x, float y, float width, float height, float dx, float dy, ushort* walls, uint walls_len, float* out_dx, float* out_dy);

        /// <summary>
        ///  Copies a region of another tilemap onto this one. `tilekey` uses a
        ///  negative `tilekey_x` as the None sentinel; `rotate` / `scale` use NaN.
        ///
        ///  # Safety
        ///  `handle` and `source` must be live tilemap handles.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_blt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_blt(void* handle, float x, float y, void* source, float u, float v, float width, float height, int tilekey_x, int tilekey_y, float rotate, float scale);

        /// <summary>
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tone_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tone_new(void** out_handle);

        /// <summary>
        ///  Returns a handle to the tone bank `pyxel.tones[index]`.
        ///
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tone_bank", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tone_bank(uint index, void** out_handle);

        /// <summary>
        ///  Number of tone banks (`pyxel::NUM_TONES`).
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_num_tones", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_num_tones(uint* out_value);

        /// <summary>
        ///  Releases the handle's `Arc` clone (safe from any thread).
        ///
        ///  # Safety
        ///  `handle` must be a live handle; it is invalid after this call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tone_drop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tone_drop(void* handle);

        /// <summary>
        ///  Tone mode (0 = wavetable, 1 = short-period noise, 2 = long-period noise).
        ///
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tone_mode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tone_mode(void* handle, uint* out_value);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tone_set_mode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tone_set_mode(void* handle, uint mode);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tone_sample_bits", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tone_sample_bits(void* handle, uint* out_value);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tone_set_sample_bits", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tone_set_sample_bits(void* handle, uint sample_bits);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tone_gain", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tone_gain(void* handle, float* out_value);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tone_set_gain", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tone_set_gain(void* handle, float gain);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_len` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tone_wavetable_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tone_wavetable_len(void* handle, uint* out_len);

        /// <summary>
        ///  Copies up to `buffer_len` wavetable samples into `buffer`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `buffer` must hold `buffer_len` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tone_wavetable_read", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tone_wavetable_read(void* handle, uint* buffer, uint buffer_len);

        /// <summary>
        ///  Replaces the wavetable with `data_len` samples from `data`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `data` must hold `data_len` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tone_wavetable_write", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tone_wavetable_write(void* handle, uint* data, uint data_len);


    }



}
