// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace PyxelSharp.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "pyxel_bind_cs";





        /// <summary>
        ///  Returns the message of the last failed call. The pointer stays valid until
        ///  the next failing call on the same thread.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_last_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* pyxel_last_error();

        /// <summary>
        ///  # Safety
        ///  `title` must be null or a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_init(uint width, uint height, byte* title, uint fps, uint quit_key, uint display_scale, uint capture_scale, uint capture_sec, int headless);

        [DllImport(__DllName, EntryPoint = "pyxel_run", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_run(delegate* unmanaged[Cdecl]<void> update, delegate* unmanaged[Cdecl]<void> draw);

        [DllImport(__DllName, EntryPoint = "pyxel_show", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_show();

        [DllImport(__DllName, EntryPoint = "pyxel_flip", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_flip();

        [DllImport(__DllName, EntryPoint = "pyxel_quit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_quit();

        /// <summary>
        ///  # Safety
        ///  `title` must be a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_title", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_title(byte* title);

        [DllImport(__DllName, EntryPoint = "pyxel_fullscreen", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_fullscreen([MarshalAs(UnmanagedType.U1)] bool enabled);

        [DllImport(__DllName, EntryPoint = "pyxel_perf_monitor", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_perf_monitor([MarshalAs(UnmanagedType.U1)] bool enabled);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_frame_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_frame_count(uint* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_width", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_width(uint* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_height", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_height(uint* out_value);

        /// <summary>
        ///  Loads a BDF or TTF font; `font_size` (NaN = default) applies to TTF.
        ///
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string; `out_handle` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_font_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_font_new(byte* filename, float font_size, void** out_handle);

        /// <summary>
        ///  Releases the handle's `Rc` clone. Must be called on the pyxel thread.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; it is invalid after this call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_font_drop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_font_drop(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle; `text` a valid NUL-terminated UTF-8
        ///  string; `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_font_text_width", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_font_text_width(void* handle, byte* text, int* out_value);

        [DllImport(__DllName, EntryPoint = "pyxel_cls", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_cls(byte color);

        /// <summary>
        ///  # Safety
        ///  `out_color` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_pget", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_pget(float x, float y, byte* out_color);

        [DllImport(__DllName, EntryPoint = "pyxel_pset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_pset(float x, float y, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_line", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_line(float x1, float y1, float x2, float y2, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_rect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_rect(float x, float y, float width, float height, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_rectb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_rectb(float x, float y, float width, float height, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_circ", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_circ(float x, float y, float radius, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_circb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_circb(float x, float y, float radius, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_elli", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_elli(float x, float y, float width, float height, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_ellib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_ellib(float x, float y, float width, float height, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_tri", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tri(float x1, float y1, float x2, float y2, float x3, float y3, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_trib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_trib(float x1, float y1, float x2, float y2, float x3, float y3, byte color);

        [DllImport(__DllName, EntryPoint = "pyxel_fill", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_fill(float x, float y, byte color);

        /// <summary>
        ///  # Safety
        ///  `text` must be a valid NUL-terminated UTF-8 string and `font` null
        ///  (built-in font) or a live font handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_text(float x, float y, byte* text, byte color, void* font);

        /// <summary>
        ///  Blits from a source image handle to the screen. `colkey` uses -1 as the
        ///  None sentinel, `rotate` / `scale` use NaN.
        ///
        ///  # Safety
        ///  `image` must be a live handle returned by one of the `pyxel_image_*` /
        ///  `pyxel_screen` constructors.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_blt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_blt(float x, float y, void* image, float u, float v, float width, float height, int colkey, float rotate, float scale);

        /// <summary>
        ///  Draws a region of a tilemap onto the screen (Python: `pyxel.bltm`).
        ///  `colkey` uses -1 as the None sentinel, `rotate` / `scale` use NaN.
        ///
        ///  # Safety
        ///  `tilemap` must be a live tilemap handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_bltm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_bltm(float x, float y, void* tilemap, float u, float v, float width, float height, int colkey, float rotate, float scale);

        /// <summary>
        ///  Perspective-projects a region of an image onto the screen
        ///  (Python: `pyxel.blt3d`). `fov` uses NaN and `colkey` -1 as None sentinels.
        ///
        ///  # Safety
        ///  `image` must be a live image handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_blt3d", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_blt3d(float x, float y, float width, float height, void* image, float pos_x, float pos_y, float pos_z, float rot_x, float rot_y, float rot_z, float fov, int colkey);

        /// <summary>
        ///  Perspective-projects a region of a tilemap onto the screen
        ///  (Python: `pyxel.bltm3d`). `fov` uses NaN and `colkey` -1 as None sentinels.
        ///
        ///  # Safety
        ///  `tilemap` must be a live tilemap handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_bltm3d", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_bltm3d(float x, float y, float width, float height, void* tilemap, float pos_x, float pos_y, float pos_z, float rot_x, float rot_y, float rot_z, float fov, int colkey);

        [DllImport(__DllName, EntryPoint = "pyxel_clip", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_clip(float x, float y, float width, float height);

        [DllImport(__DllName, EntryPoint = "pyxel_clip_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_clip_reset();

        [DllImport(__DllName, EntryPoint = "pyxel_camera", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_camera(float x, float y);

        [DllImport(__DllName, EntryPoint = "pyxel_camera_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_camera_reset();

        [DllImport(__DllName, EntryPoint = "pyxel_dither", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_dither(float alpha);

        [DllImport(__DllName, EntryPoint = "pyxel_pal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_pal(byte src_color, byte dst_color);

        [DllImport(__DllName, EntryPoint = "pyxel_pal_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_pal_reset();

        /// <summary>
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_new(uint width, uint height, void** out_handle);

        /// <summary>
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string and `out_handle`
        ///  must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_from_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_from_image(byte* filename, int include_colors, void** out_handle);

        /// <summary>
        ///  Returns a handle to the image bank `pyxel.images[index]`.
        ///
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_bank", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_bank(uint index, void** out_handle);

        /// <summary>
        ///  Returns a handle to the screen image `pyxel.screen`.
        ///
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_screen", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_screen(void** out_handle);

        /// <summary>
        ///  Number of image banks (`pyxel::NUM_IMAGES`).
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_num_images", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_num_images(uint* out_value);

        /// <summary>
        ///  Releases the handle's `Rc` clone. Must be called on the pyxel thread.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; it is invalid after this call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_drop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_drop(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_width", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_width(void* handle, uint* out_value);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_height", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_height(void* handle, uint* out_value);

        /// <summary>
        ///  Pointer to the image's pixel buffer (`width * height` color indices).
        ///  Valid while the image is alive and its size unchanged.
        ///
        ///  # Safety
        ///  `handle` must be a live handle and `out_ptr` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_data_ptr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_data_ptr(void* handle, byte** out_ptr);

        /// <summary>
        ///  Writes rows of hex color digits (`data`, `data_len` strings) at (x, y),
        ///  like Python's `image.set`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `data` must point to `data_len` valid
        ///  NUL-terminated UTF-8 strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_set", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_set(void* handle, int x, int y, byte** data, uint data_len);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `filename` a valid NUL-terminated
        ///  UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_load", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_load(void* handle, int x, int y, byte* filename, int include_colors);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `filename` a valid NUL-terminated
        ///  UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_save", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_save(void* handle, byte* filename, uint scale);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_clip", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_clip(void* handle, float x, float y, float width, float height);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_clip_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_clip_reset(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_camera", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_camera(void* handle, float x, float y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_camera_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_camera_reset(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_pal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_pal(void* handle, byte src_color, byte dst_color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_pal_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_pal_reset(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_dither", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_dither(void* handle, float alpha);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_cls", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_cls(void* handle, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_color` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_pget", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_pget(void* handle, float x, float y, byte* out_color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_pset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_pset(void* handle, float x, float y, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_line", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_line(void* handle, float x1, float y1, float x2, float y2, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_rect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_rect(void* handle, float x, float y, float width, float height, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_rectb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_rectb(void* handle, float x, float y, float width, float height, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_circ", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_circ(void* handle, float x, float y, float radius, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_circb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_circb(void* handle, float x, float y, float radius, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_elli", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_elli(void* handle, float x, float y, float width, float height, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_ellib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_ellib(void* handle, float x, float y, float width, float height, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_tri", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_tri(void* handle, float x1, float y1, float x2, float y2, float x3, float y3, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_trib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_trib(void* handle, float x1, float y1, float x2, float y2, float x3, float y3, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_fill", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_fill(void* handle, float x, float y, byte color);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle, `text` a valid NUL-terminated UTF-8
        ///  string, and `font` null (built-in font) or a live font handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_text(void* handle, float x, float y, byte* text, byte color, void* font);

        /// <summary>
        ///  Draws a region of a tilemap onto `handle` (Python: &lt;c&gt;image.bltm&lt;/c&gt;).
        ///  `colkey` uses -1 as the None sentinel, `rotate` / `scale` use NaN.
        ///
        ///  # Safety
        ///  `handle` must be a live image handle and `tilemap` a live tilemap handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_bltm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_bltm(void* handle, float x, float y, void* tilemap, float u, float v, float width, float height, int colkey, float rotate, float scale);

        /// <summary>
        ///  Perspective-projects a region of a source image onto `handle`
        ///  (Python: `image.blt3d`). `fov` uses NaN and `colkey` -1 as None sentinels.
        ///
        ///  # Safety
        ///  `handle` and `source` must be live image handles.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_blt3d", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_blt3d(void* handle, float x, float y, float width, float height, void* source, float pos_x, float pos_y, float pos_z, float rot_x, float rot_y, float rot_z, float fov, int colkey);

        /// <summary>
        ///  Perspective-projects a region of a tilemap onto `handle`
        ///  (Python: `image.bltm3d`). `fov` uses NaN and `colkey` -1 as None sentinels.
        ///
        ///  # Safety
        ///  `handle` must be a live image handle and `tilemap` a live tilemap handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_bltm3d", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_bltm3d(void* handle, float x, float y, float width, float height, void* tilemap, float pos_x, float pos_y, float pos_z, float rot_x, float rot_y, float rot_z, float fov, int colkey);

        /// <summary>
        ///  Blits from `source` onto `handle`. `colkey` uses -1 as the None sentinel,
        ///  `rotate` / `scale` use NaN.
        ///
        ///  # Safety
        ///  `handle` and `source` must be live handles.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_image_blt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_image_blt(void* handle, float x, float y, void* source, float u, float v, float width, float height, int colkey, float rotate, float scale);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_btn", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_btn(uint key, bool* out_value);

        /// <summary>
        ///  `hold_frames` / `repeat_frames` use `u32::MAX` as the None sentinel.
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_btnp", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_btnp(uint key, uint hold_frames, uint repeat_frames, bool* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_btnr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_btnr(uint key, bool* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_btnv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_btnv(uint key, int* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_mouse_x", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_mouse_x(int* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_mouse_y", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_mouse_y(int* out_value);

        /// <summary>
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_mouse_wheel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_mouse_wheel(int* out_value);

        [DllImport(__DllName, EntryPoint = "pyxel_mouse", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_mouse([MarshalAs(UnmanagedType.U1)] bool visible);

        [DllImport(__DllName, EntryPoint = "pyxel_warp_mouse", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_warp_mouse(float x, float y);

        /// <summary>
        ///  Loads a .pyxres resource file. The `exclude_*` flags are `i32` opt-bools
        ///  (-1 = None).
        ///
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_load", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_load(byte* filename, int exclude_images, int exclude_tilemaps, int exclude_sounds, int exclude_musics);

        /// <summary>
        ///  Saves a .pyxres resource file. The `exclude_*` flags are `i32` opt-bools
        ///  (-1 = None).
        ///
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_save", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_save(byte* filename, int exclude_images, int exclude_tilemaps, int exclude_sounds, int exclude_musics);

        /// <summary>
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_load_pal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_load_pal(byte* filename);

        /// <summary>
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_save_pal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_save_pal(byte* filename);

        /// <summary>
        ///  Saves a screenshot; a null `filename` uses a timestamped desktop path.
        ///  `scale` uses `u32::MAX` as the None sentinel.
        ///
        ///  # Safety
        ///  `filename` must be null or a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_screenshot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_screenshot(byte* filename, uint scale);

        /// <summary>
        ///  Saves the recent frames as a GIF; a null `filename` uses a timestamped
        ///  desktop path. `scale` uses `u32::MAX` as the None sentinel.
        ///
        ///  # Safety
        ///  `filename` must be null or a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_screencast", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_screencast(byte* filename, uint scale);

        [DllImport(__DllName, EntryPoint = "pyxel_reset_screencast", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_reset_screencast();

        /// <summary>
        ///  Returns the per-user data directory for the app. The pointer written to
        ///  `out_path` stays valid until the next string-returning call on this thread.
        ///
        ///  # Safety
        ///  `vendor_name` and `app_name` must be valid NUL-terminated UTF-8 strings;
        ///  `out_path` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_user_data_dir", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_user_data_dir(byte* vendor_name, byte* app_name, byte** out_path);

        /// <summary>
        ///  Creates a tilemap whose tiles reference either the image bank `image_index`
        ///  (when `image` is null) or the given image handle.
        ///
        ///  # Safety
        ///  `image` must be null or a live image handle; `out_handle` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_new(uint width, uint height, void* image, uint image_index, void** out_handle);

        /// <summary>
        ///  # Safety
        ///  `filename` must be a valid NUL-terminated UTF-8 string; `out_handle` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_from_tmx", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_from_tmx(byte* filename, uint layer, void** out_handle);

        /// <summary>
        ///  Returns a handle to the tilemap bank `pyxel.tilemaps[index]`.
        ///
        ///  # Safety
        ///  `out_handle` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_bank", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_bank(uint index, void** out_handle);

        /// <summary>
        ///  Number of tilemap banks (`pyxel::NUM_TILEMAPS`).
        ///
        ///  # Safety
        ///  `out_value` must point to writable memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_num_tilemaps", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_num_tilemaps(uint* out_value);

        /// <summary>
        ///  Releases the handle's `Rc` clone. Must be called on the pyxel thread.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; it is invalid after this call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_drop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_drop(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_width", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_width(void* handle, uint* out_value);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `out_value` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_height", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_height(void* handle, uint* out_value);

        /// <summary>
        ///  Reads the image source: bank index into `out_index` (with `out_image` set
        ///  to null), or a new image handle into `out_image` (with `out_index` -1).
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `out_index` and `out_image` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_imgsrc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_imgsrc(void* handle, int* out_index, void** out_image);

        /// <summary>
        ///  Points the tilemap at an image bank or (non-null `image`) an image handle.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `image` null or a live image handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_set_imgsrc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_set_imgsrc(void* handle, void* image, uint image_index);

        /// <summary>
        ///  Pointer to the tile buffer (`width * height` tiles, two u16 each).
        ///  Valid while the tilemap is alive and its size unchanged.
        ///
        ///  # Safety
        ///  `handle` must be a live handle and `out_ptr` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_data_ptr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_data_ptr(void* handle, ushort** out_ptr);

        /// <summary>
        ///  Writes rows of tile data at (x, y), like Python's `tilemap.set`.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `data` must point to `data_len` valid
        ///  NUL-terminated UTF-8 strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_set", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_set(void* handle, int x, int y, byte** data, uint data_len);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle and `filename` a valid NUL-terminated
        ///  UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_load", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_load(void* handle, int x, int y, byte* filename, uint layer);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_clip", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_clip(void* handle, float x, float y, float width, float height);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_clip_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_clip_reset(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_camera", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_camera(void* handle, float x, float y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_camera_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_camera_reset(void* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_cls", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_cls(void* handle, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle; `out_tile_x` and `out_tile_y` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_pget", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_pget(void* handle, float x, float y, ushort* out_tile_x, ushort* out_tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_pset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_pset(void* handle, float x, float y, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_line", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_line(void* handle, float x1, float y1, float x2, float y2, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_rect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_rect(void* handle, float x, float y, float width, float height, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_rectb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_rectb(void* handle, float x, float y, float width, float height, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_circ", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_circ(void* handle, float x, float y, float radius, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_circb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_circb(void* handle, float x, float y, float radius, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_elli", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_elli(void* handle, float x, float y, float width, float height, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_ellib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_ellib(void* handle, float x, float y, float width, float height, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_tri", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_tri(void* handle, float x1, float y1, float x2, float y2, float x3, float y3, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_trib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_trib(void* handle, float x1, float y1, float x2, float y2, float x3, float y3, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  # Safety
        ///  `handle` must be a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_fill", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_fill(void* handle, float x, float y, ushort tile_x, ushort tile_y);

        /// <summary>
        ///  Slides a rect by (dx, dy) against wall tiles, returning the allowed
        ///  movement (Python: `tilemap.collide`). `walls` is `walls_len` tiles laid
        ///  out as u16 pairs.
        ///
        ///  # Safety
        ///  `handle` must be a live handle; `walls` must point to `walls_len * 2`
        ///  u16 values; `out_dx` and `out_dy` writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_collide", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_collide(void* handle, float x, float y, float width, float height, float dx, float dy, ushort* walls, uint walls_len, float* out_dx, float* out_dy);

        /// <summary>
        ///  Copies a region of another tilemap onto this one. `tilekey` uses a
        ///  negative `tilekey_x` as the None sentinel; `rotate` / `scale` use NaN.
        ///
        ///  # Safety
        ///  `handle` and `source` must be live tilemap handles.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pyxel_tilemap_blt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int pyxel_tilemap_blt(void* handle, float x, float y, void* source, float u, float v, float width, float height, int tilekey_x, int tilekey_y, float rotate, float scale);


    }



}
