#!/usr/bin/env bash
# Generate-KeyEnum.ps1 の macOS/Linux 版。pyxel-core の key.rs から
# csharp/src/PyxelSharp/Key.g.cs を生成する (python3 使用; Xcode CLT 同梱で可)。
#
#   tools/Generate-KeyEnum.sh [<key.rs> [<out.cs>]]
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
key_rs="${1:-$repo_root/pyxel/crates/pyxel-core/src/platform/key.rs}"
out_file="${2:-$repo_root/csharp/src/PyxelSharp/Key.g.cs}"

python3 - "$key_rs" "$out_file" <<'PYEOF'
import re
import sys

key_rs, out_file = sys.argv[1], sys.argv[2]

# 範囲定義用の補助定数。enum には含めないが後続定数の式では参照できる
HELPER_NAMES = {
    "VIRTUAL_KEY_START_INDEX", "MOUSE_KEY_START_INDEX",
    "GAMEPAD_KEY_START_INDEX", "GAMEPAD_KEY_STRIDE", "GAMEPAD_AXIS_COUNT",
}

def member_name(const_name):
    name = re.sub(r"^KEY_", "", const_name)
    tokens = [t for t in name.split("_") if t]
    pascal = "".join(t if t[0].isdigit() else t[0].upper() + t[1:].lower()
                     for t in tokens)
    if pascal[0].isdigit():
        pascal = "D" + pascal
    return pascal

values = {}   # 定数名 -> 値 (補助定数を含む)
members = []  # (メンバー名, 値)

def resolve_expr(expr):
    expr = expr.strip()
    # 既知の識別子を値に置換。lookbehind で 0x0D 等リテラル内の英字を除外
    def sub_ident(m):
        if m.group(0) in values:
            return str(values[m.group(0)])
        raise SystemExit(f"Unknown identifier '{m.group(0)}' in expression '{expr}'")
    expr = re.sub(r"(?<!\w)[A-Z][A-Z0-9_]*", sub_ident, expr)
    expr = re.sub(r"0x[0-9A-Fa-f_]+", lambda m: m.group(0).replace("_", ""), expr)
    return eval(expr, {"__builtins__": {}}, {})

def add_const(name, value):
    values[name] = value
    if name not in HELPER_NAMES:
        members.append((member_name(name), value))

with open(key_rs, encoding="utf-8") as f:
    for line in f:
        m = re.match(r"^\s*pub const (\w+): Key = (.+);\s*$", line)
        if m:
            add_const(m.group(1), resolve_expr(m.group(2)))

# define_gamepad_keys! マクロの展開 (行パーサでは見えない paste 生成分)。
# オフセットは key.rs に従う
GAMEPAD_SUFFIXES = [
    "AXIS_LEFTX", "AXIS_LEFTY", "AXIS_RIGHTX", "AXIS_RIGHTY",
    "AXIS_TRIGGERLEFT", "AXIS_TRIGGERRIGHT",
    "BUTTON_A", "BUTTON_B", "BUTTON_X", "BUTTON_Y",
    "BUTTON_BACK", "BUTTON_GUIDE", "BUTTON_START",
    "BUTTON_LEFTSTICK", "BUTTON_RIGHTSTICK",
    "BUTTON_LEFTSHOULDER", "BUTTON_RIGHTSHOULDER",
    "BUTTON_DPAD_UP", "BUTTON_DPAD_DOWN", "BUTTON_DPAD_LEFT", "BUTTON_DPAD_RIGHT",
]
start = values["GAMEPAD_KEY_START_INDEX"]
stride = values["GAMEPAD_KEY_STRIDE"]
for pad in range(1, 5):
    base = start + stride * (pad - 1)
    for i, suffix in enumerate(GAMEPAD_SUFFIXES):
        add_const(f"GAMEPAD{pad}_{suffix}", base + i)

lines = [
    "// <auto-generated>",
    "// Generated by tools/Generate-KeyEnum.ps1 from pyxel-core/src/platform/key.rs.",
    "// Do not edit by hand.",
    "// </auto-generated>",
    "",
    "namespace PyxelSharp;",
    "",
    "/// <summary>",
    "/// Key codes for input APIs. Mirrors pyxel's Key constants; mouse buttons and",
    "/// gamepad buttons share the same key space, as in pyxel itself.",
    "/// </summary>",
    "public enum Key : uint",
    "{",
]
lines += [f"    {name} = 0x{value:08X}," for name, value in members]
lines += ["}", "", ""]  # Set-Content 由来の末尾空行に合わせて 2 つ

with open(out_file, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print(f"Generated {out_file} ({len(members)} members)")
PYEOF
