# Generates csharp/src/PyxelSharp/Key.g.cs from pyxel-core's key constants.
# Re-run after updating the pyxel submodule if key.rs changed.
param(
    [string]$KeyRs = "$PSScriptRoot\..\pyxel\crates\pyxel-core\src\platform\key.rs",
    [string]$OutFile = "$PSScriptRoot\..\csharp\src\PyxelSharp\Key.g.cs"
)

$ErrorActionPreference = 'Stop'

# Helper constants that define ranges, not keys; excluded from the enum but
# usable in expressions of later constants.
$helperNames = @(
    'VIRTUAL_KEY_START_INDEX', 'MOUSE_KEY_START_INDEX',
    'GAMEPAD_KEY_START_INDEX', 'GAMEPAD_KEY_STRIDE', 'GAMEPAD_AXIS_COUNT'
)

function ConvertTo-MemberName([string]$constName) {
    $name = $constName -replace '^KEY_', ''
    $tokens = $name -split '_' | Where-Object { $_ -ne '' }
    $pascal = ($tokens | ForEach-Object {
        if ($_ -match '^\d') { $_ }
        else { $_.Substring(0, 1).ToUpper() + $_.Substring(1).ToLower() }
    }) -join ''
    if ($pascal -match '^\d') { $pascal = 'D' + $pascal }
    $pascal
}

$values = @{}          # const name -> uint64 value (includes helpers)
$members = [System.Collections.Generic.List[pscustomobject]]::new()

function Resolve-Expr([string]$expr) {
    $expr = $expr.Trim()
    # Replace known identifiers with their values. The lookbehind keeps hex
    # digits inside literals like 0x0D from matching as identifiers.
    $expr = [regex]::Replace($expr, '(?<!\w)[A-Z][A-Z0-9_]*', {
        param($m)
        if ($values.ContainsKey($m.Value)) { [string]$values[$m.Value] }
        else { throw "Unknown identifier '$($m.Value)' in expression '$expr'" }
    })
    # Hex literals with underscores -> plain hex
    $expr = [regex]::Replace($expr, '0x[0-9A-Fa-f_]+', { param($m) ($m.Value -replace '_', '') })
    [uint64](Invoke-Expression $expr)
}

function Add-Const([string]$name, [uint64]$value) {
    $values[$name] = $value
    if ($helperNames -notcontains $name) {
        $members.Add([pscustomobject]@{ Name = (ConvertTo-MemberName $name); Value = $value; Source = $name })
    }
}

foreach ($line in Get-Content $KeyRs) {
    if ($line -match '^\s*pub const (\w+): Key = (.+);\s*$') {
        Add-Const $Matches[1] (Resolve-Expr $Matches[2])
    }
}

# Expand the define_gamepad_keys! macro (paste-generated, not visible to the
# line-based parser above). Offsets follow key.rs.
$gamepadSuffixes = @(
    'AXIS_LEFTX', 'AXIS_LEFTY', 'AXIS_RIGHTX', 'AXIS_RIGHTY',
    'AXIS_TRIGGERLEFT', 'AXIS_TRIGGERRIGHT',
    'BUTTON_A', 'BUTTON_B', 'BUTTON_X', 'BUTTON_Y',
    'BUTTON_BACK', 'BUTTON_GUIDE', 'BUTTON_START',
    'BUTTON_LEFTSTICK', 'BUTTON_RIGHTSTICK',
    'BUTTON_LEFTSHOULDER', 'BUTTON_RIGHTSHOULDER',
    'BUTTON_DPAD_UP', 'BUTTON_DPAD_DOWN', 'BUTTON_DPAD_LEFT', 'BUTTON_DPAD_RIGHT'
)
$gamepadStart = $values['GAMEPAD_KEY_START_INDEX']
$gamepadStride = $values['GAMEPAD_KEY_STRIDE']
foreach ($pad in 1..4) {
    $base = $gamepadStart + $gamepadStride * ($pad - 1)
    for ($i = 0; $i -lt $gamepadSuffixes.Count; $i++) {
        Add-Const "GAMEPAD$($pad)_$($gamepadSuffixes[$i])" ($base + $i)
    }
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('// Generated by tools/Generate-KeyEnum.ps1 from pyxel-core/src/platform/key.rs.')
[void]$sb.AppendLine('// Do not edit by hand.')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace PyxelSharp;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('/// <summary>')
[void]$sb.AppendLine('/// Key codes for input APIs. Mirrors pyxel''s Key constants; mouse buttons and')
[void]$sb.AppendLine('/// gamepad buttons share the same key space, as in pyxel itself.')
[void]$sb.AppendLine('/// </summary>')
[void]$sb.AppendLine('public enum Key : uint')
[void]$sb.AppendLine('{')
foreach ($m in $members) {
    [void]$sb.AppendLine(('    {0} = 0x{1:X8},' -f $m.Name, $m.Value))
}
[void]$sb.AppendLine('}')

New-Item -ItemType Directory -Force (Split-Path $OutFile) | Out-Null
Set-Content -Path $OutFile -Value $sb.ToString() -Encoding utf8NoBOM
Write-Host "Generated $OutFile ($($members.Count) members)"
